name             'cakephp'
maintainer       'And Works, Inc.'
maintainer_email 'ando@and-works.co.jp'
license          'All rights reserved'
description      'Installs/Configures cakephp-website'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'database'
depends 'apache2'
depends 'iptables'
depends 'mysql'
depends 'php'
depends 'vim'
depends 'yum'
depends 'mongodb'